version: '3.1'

services:
  database:
    image: mysql:8.0.22
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
  app:
    depends_on:
      - database
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mysql
      - DATABASE_PORT=3306

